--- #deployemnet play-book

- hosts: Dev, QA
  user: service
  become: yes
  connection: ssh
  gather_facts: yes

  tasks:
    - name: Copy a directory to a remote machine
      copy: src=/mnt/project/ dest=/home/service

    - name: install docker
      command: yum install docker -y

    - name: start docker
      command: systemctl start docker

    - name: run docker-compose file
      command: docker-compose up -d
