--- #deployemnet play-book

- hosts: qa, dev
  user: service
  become: true
  connection: ssh
  gather_facts: yes

  tasks:
    - name: Copy a directory to a remote machine
      copy: src=/mnt/project/ dest=/home/service

    - name: install docker
      command: yum install docker -y

    - name: start docker
      command: systemctl start docker

    - name: stopping the existing containers
      command: docker-compose down

    - name: Removing existing images
      command: docker system prune -af

    - name: run docker-compose file
      command: sudo docker-compose up -d
